[package]
name = "kalc-plot"
version = "0.1.1"
edition = "2024"
license = "GPL-3.0-only"
description = "a complex graphing gui"
authors = ["bgkillas <mswalhelm@gmail.com>"]

[features]
default=["egui"]
egui=["dep:egui","dep:eframe","rupl/egui"]
skia=["rupl/skia" ,"rupl/winit", "dep:winit", "dep:softbuffer"]

[dependencies]
egui={version="0.31.1",optional=true}
eframe={version="0.31.1",optional=true}
winit={version="0.30.9",optional=true}
softbuffer={version="0.4.6",optional=true}
rupl={path="../rupl",default-features = false}
rug="1.27.0"
rayon="1.10.0"
serde_json = "1.0.140"
kalc-lib={path="../kalc-lib"}