[package]
name = "kalc-plot"
version = "0.1.0"
edition = "2024"
license = "GPL-3.0-only"
description = "a complex graphing gui"
authors = ["bgkillas <mswalhelm@gmail.com>"]

[features]
default=["skia"]
egui=["dep:egui", "dep:eframe", "rupl/egui"]
skia=["rupl/skia", "dep:winit"]

[dependencies]
egui={version="0.31.1",optional=true}
eframe={version="0.31.1",optional=true}
winit={version="0.30.9",optional=true}
rupl={path="../rupl",default-features = false}#git="https://github.com/bgkillas/rupl"}
rug="1.27.0"
rayon="1.10.0"
kalc-lib={git="https://github.com/bgkillas/kalc-lib"}