[package]
name = "kalc-plot"
version = "0.1.0"
edition = "2024"
license = "GPL-3.0-only"
description = "a complex graphing gui"
authors = ["bgkillas <mswalhelm@gmail.com>"]

[dependencies]
egui="0.31.1"
eframe="0.31.1"
rupl={git="https://github.com/bgkillas/rupl"}
rug="1.27.0"
rayon="1.10.0"
kalc-lib={git="https://github.com/bgkillas/kalc-lib"}