[package]
name = "kalc-plot"
version = "0.1.1"
edition = "2024"
license = "GPL-3.0-only"
description = "a complex graphing gui"
authors = ["bgkillas <mswalhelm@gmail.com>"]
repository = "https://github.com/bgkillas/kalc-plot"
homepage = "https://github.com/bgkillas/kalc-plot"

[features]
default=["skia"]
egui=["dep:egui","dep:eframe","rupl/egui"]
skia=["rupl/skia" ,"rupl/winit", "dep:winit", "dep:softbuffer"]

[dependencies]
egui={version="0.31.1",optional=true}
eframe={version="0.31.1",optional=true}
winit={version="0.30.9",optional=true}
softbuffer={version="0.4.6",optional=true}
rug="1.27.0"
rayon="1.10.0"
serde_json = "1.0.140"
rupl={version = "0.1.1",path="../rupl",default-features = false}
kalc-lib={version="1.5.0",path="../kalc-lib"}