name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-egui:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: depends
      run: |
        cd ..
        git clone https://github.com/bgkillas/rupl
        git clone https://github.com/bgkillas/kalc-lib
        cd kalc-plot
    - name: Build egui
      run: cargo build --no-default-features --features "egui,rug,fastnum"
    - name: Build egui-full
      run: cargo build --no-default-features --features "egui,rayon,bincode,rug,fastnum"
    - name: Run tests egui
      run: cargo test --no-default-features --features "egui,rug,fastnum"
  build-skia:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y libwayland-dev libxkbcommon-dev pkg-config libudev-dev libinput-dev libdrm-dev libgbm-dev build-essential
    - name: depends
      run: |
        cd ..
        git clone https://github.com/bgkillas/rupl
        git clone https://github.com/bgkillas/kalc-lib
        cd kalc-plot
    - name: deps
      run: |
        sudo apt update
        sudo apt install libfontconfig1-dev libfreetype6-dev
    - name: Build skia
      run: cargo build --no-default-features --features "skia,wayland, softbuffer, softbuffer-wayland,rug,fastnum"
    - name: Build skia-vulkan
      run: cargo build --no-default-features --features "skia,skia-vulkan,wayland,rug,fastnum"
    - name: Build skia-full
      run: cargo build --no-default-features --features "skia,skia-vulkan,arboard,rayon,bincode,wayland,rug,fastnum"
    - name: Run tests skia
      run: cargo test --no-default-features --features "skia,wayland, softbuffer, softbuffer-wayland,rug,fastnum"
  build-tiny-skia:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y libwayland-dev libxkbcommon-dev pkg-config libudev-dev libinput-dev libdrm-dev libgbm-dev build-essential
    - name: depends
      run: |
        cd ..
        git clone https://github.com/bgkillas/rupl
        git clone https://github.com/bgkillas/kalc-lib
        cd kalc-plot
    - name: Build tiny-skia
      run: cargo build --no-default-features --features "tiny-skia,wayland, softbuffer, softbuffer-wayland,rug,fastnum"
    - name: Build tiny-full
      run: cargo build --no-default-features --features "tiny-skia,arboard,rayon,bincode,wayland, softbuffer, softbuffer-wayland,rug,fastnum"
    - name: Run tests tiny-skia
      run: cargo test --no-default-features --features "tiny-skia,wayland, softbuffer, softbuffer-wayland,rug,fastnum"
  lint:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
       - name: Install dependencies
         run: sudo apt-get update && sudo apt-get install -y libwayland-dev libxkbcommon-dev pkg-config libudev-dev libinput-dev libdrm-dev libgbm-dev build-essential
       - name: depends
         run: |
           cd ..
           git clone https://github.com/bgkillas/rupl
           git clone https://github.com/bgkillas/kalc-lib
           cd kalc-plot
       - name: fmt
         run: cargo fmt --check
       - name: lint-vulkan
         run: cargo clippy --no-default-features --features "skia,skia-vulkan,arboard,rayon,bincode,wayland,rug,fastnum"
       - name: lint-skia
         run: cargo clippy --no-default-features --features "skia,arboard,rayon,bincode,wayland,softbuffer,softbuffer-wayland,rug,fastnum"
       - name: lint-skia-min
         run: cargo clippy --no-default-features --features "skia,wayland,softbuffer,softbuffer-wayland,rug,fastnum"
       - name: lint-tiny
         run: cargo clippy --no-default-features --features "tiny-skia,arboard,rayon,bincode,wayland,softbuffer,softbuffer-wayland,rug,fastnum"
       - name: lint-egui
         run: cargo clippy --no-default-features --features "egui,rayon,bincode,rug,fastnum"
  build-windows:
     runs-on: windows-latest
     steps:
       - uses: actions/checkout@v4
       - name: depends
         run: |
           cd ..
           git clone https://github.com/bgkillas/rupl
           git clone https://github.com/bgkillas/kalc-lib
           cd kalc-plot
       - name: Install Rust
         uses: actions-rs/toolchain@v1
         with:
          toolchain: stable
          target: x86_64-pc-windows-gnu
          profile: minimal
          override: true
       - name: Install MSYS2 and GMP
         uses: msys2/setup-msys2@v2
         with:
          update: true
          install: >-
           mingw-w64-x86_64-gmp
          msystem: MINGW64
       - name: fmt
         run: cargo fmt --check
       - name: lint-vulkan
         run: cargo clippy --no-default-features --features "skia,skia-vulkan,arboard,rayon,bincode,rug,fastnum" --target x86_64-pc-windows-gnu
       - name: lint-skia
         run: cargo clippy --no-default-features --features "skia,arboard,rayon,bincode,softbuffer,rug,fastnum" --target x86_64-pc-windows-gnu
       - name: lint-skia-min
         run: cargo clippy --no-default-features --features "skia,softbuffer,rug,fastnum" --target x86_64-pc-windows-gnu
       - name: lint-tiny
         run: cargo clippy --no-default-features --features "tiny-skia,arboard,rayon,bincode,softbuffer,rug,fastnum" --target x86_64-pc-windows-gnu
       - name: lint-egui
         run: cargo clippy --no-default-features --features "egui,rayon,bincode,rug,fastnum" --target x86_64-pc-windows-gnu
  build-macos:
     runs-on: macos-latest
     steps:
       - uses: actions/checkout@v4
       - name: depends
         run: |
           cd ..
           git clone https://github.com/bgkillas/rupl
           git clone https://github.com/bgkillas/kalc-lib
           cd kalc-plot
       - name: fmt
         run: cargo fmt --check
       - name: lint-vulkan
         run: cargo clippy --no-default-features --features "skia,skia-vulkan,arboard,rayon,bincode,rug,fastnum"
       - name: lint-skia
         run: cargo clippy --no-default-features --features "skia,arboard,rayon,bincode,softbuffer,rug,fastnum"
       - name: lint-skia-min
         run: cargo clippy --no-default-features --features "skia,softbuffer,rug,fastnum"
       - name: lint-tiny
         run: cargo clippy --no-default-features --features "tiny-skia,arboard,rayon,bincode,softbuffer,rug,fastnum"
       - name: lint-egui
         run: cargo clippy --no-default-features --features "egui,rayon,bincode,rug,fastnum"