name: Build and Deploy WASM app

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          override: true

      - name: Install wasm-pack
        run: cargo install wasm-pack

      - name: depends
        run: |
          cd ..
          git clone https://github.com/bgkillas/rupl
          git clone https://github.com/bgkillas/kalc-lib
          cd kalc-plot
      - name: fmt
        run: cargo fmt --check
      - name: lint-vulkan
        run: cargo clippy --no-default-features --features "tiny-skia,wasm,rayon" -- -D clippy::all

      - name: Build WASM app
        run: |
          wasm-pack build --out-dir www/pkg --target web --release --no-default-features --features "tiny-skia,wasm,rayon"

      - name: Copy site files to output
        run: |
          mkdir dist
          cp -r www/* dist/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4